# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
#
# Copyright (c) 2026 Chengdu Changshu Robot Co., Ltd.
# https://www.openarmx.com
#
# This work is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike
# 4.0 International License (CC BY-NC-SA 4.0).
# To view a copy of this license, visit:
#
# http://creativecommons.org/licenses/by-nc-sa/4.0/
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND.



# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_joint_trajectory_controller
    - right_joint_trajectory_controller
    - left_gripper_controller
    - right_gripper_controller

  left_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - openarmx_left_joint1
      - openarmx_left_joint2
      - openarmx_left_joint3
      - openarmx_left_joint4
      - openarmx_left_joint5
      - openarmx_left_joint6
      - openarmx_left_joint7
    action_ns: follow_joint_trajectory
    default: true
  right_joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - openarmx_right_joint1
      - openarmx_right_joint2
      - openarmx_right_joint3
      - openarmx_right_joint4
      - openarmx_right_joint5
      - openarmx_right_joint6
      - openarmx_right_joint7
    action_ns: follow_joint_trajectory
    default: true
  left_gripper_controller:
    type: GripperCommand
    joints:
      - openarmx_left_finger_joint1
    action_ns: gripper_cmd
    default: true
  right_gripper_controller:
    type: GripperCommand
    joints:
      - openarmx_right_finger_joint1
    action_ns: gripper_cmd
    default: true
